# Generated by Django 5.2.15 on 2026-06-29 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_scenerun_run_id_interrupted_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenerun',
            name='scratch_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='scenerun',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scenes.scene'),
        ),
    ]
