# Generated by Django 5.2.15 on 2026-06-25 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('manager', 'Manager')], default='author', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pre-authorization',
                'verbose_name_plural': 'Pre-authorizations',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('author', 'Author'), ('manager', 'Manager')], default='author', max_length=20)),
                ('google_id', models.CharField(blank=True, max_length=100)),
                ('picture_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
