services:
  mundorum-dbms:
    image: postgres
    container_name: mundorum-dbms
    volumes:
      - mundorum-db:/var/lib/postgresql/data
    restart: on-failure:5
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  mundorum-db:
    driver: "local"
    driver_opts:
      type: "none"
      device: "/home/user/data/pgsql/mundorum-db"
      o: "bind" 

