# Generated by Django 5.2.15 on 2026-07-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('csv', 'CSV'), ('python', 'Python'), ('text', 'Text'), ('html_app', 'HTML App'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
